### ISSUE TITLE
docker版本安装后无法解锁

### ISSUE THREAD

**Issue by njgdl1995** [YukiCoco/EmbyCrack#1]
docker版本安装后高级版秘钥输入进去无任何提示

**Comment by YukiCoco** [comment]
只要显示忘记密钥就已经完成了，如下图
![image](https://user-images.githubusercontent.com/18544362/88357006-569ddd00-cd9c-11ea-8302-078d69e69e98.png)
浏览器别忘了安装插件重定向

**Comment by njgdl1995** [comment]
好的。多谢
