### ISSUE TITLE
群晖emby

### ISSUE THREAD

**Issue by damntonight** [YukiCoco/EmbyCrack#3]
hello，已经star
黑群晖emby的安装目录没有找到，不知道应该如何替换~

**Comment by YukiCoco** [comment]
参考 [博客](https://neko.re/archives/128.html) 的详细教程

**Comment by damntonight** [comment]
已经进行替换了，emby显示有黄标，但是“缺少或无效的emby高级版密钥”

**Comment by YukiCoco** [comment]
是不是服务端和电脑以前修改过 hosts，需要改回来

**Comment by damntonight** [comment]
电脑、路由器、群晖的hosts文件都没有修改过，可能是我其他设置没有做好，我再排除一下错误

**Comment by damntonight** [comment]
我连 /volume1/@appstore/EmbyServer/server/ 下的System.Net.Http.dll也替换掉了，可能是这里的原因，但是难就难在我mv之后没有备份源文件……
