### ISSUE TITLE
群晖套件emby

### ISSUE THREAD

**Issue by xiao-zl** [YukiCoco/EmbyCrack#5]
使用docker可以破解，但是套件时替换/var/packages/EmbyServer/target/server这路径后，访问网页显示Failure has occurred while loading a type.这怎么解决呢

**Comment by YukiCoco** [comment]
套件的 emby 是什么版本

**Comment by Xzhiliu** [comment]
4.4.3.0

**Comment by Xzhiliu** [comment]
还有奇怪的是套件的embyserver是exe文件，那我应该是用哪个破解呢

**Comment by YukiCoco** [comment]
> 还有奇怪的是套件的embyserver是exe文件，那我应该是用哪个破解呢

下载 Windows 的程序集

**Comment by Xzhiliu** [comment]
试过，也不可以

**Comment by YukiCoco** [comment]
> 试过，也不可以

你机器的 CPU 架构是？

**Comment by xiao-zl** [comment]
> > 试过，也不可以
> 
> 你机器的 CPU 架构是？

j3455

**Comment by YukiCoco** [comment]
只能使用 docker 版了，套件版失效原因不明。
