### ISSUE TITLE
使用Https协议无法破解

### ISSUE THREAD

**Issue by haochiang** [YukiCoco/EmbyCrack#8]
破解后在localhost:80端口打开完全没问题，不过我用ddns远程连接的时候是使用的https协议，这种情况下外网打开就显示的是没有破解，请问这种情况下如何处理呢？

**Comment by YukiCoco** [comment]
>浏览器：安装 URLRedirector 插件，将 https://mb3admin.com 替换为 http://crackemby.neko.re
将 `http://crackemby.neko.re` 替换为 `https://crackemby.neko.re` 看看

**Comment by haochiang** [comment]
如您所言，已经解决，感谢
